### PR TITLE
Atmel RF: Init RF config using named fields

### PR DESCRIPTION
**Pull request by JarkkoPaso**

### CODE REVIEW

**Comment by JarkkoPaso** [comment]
@artokin @mikter @juhhei01 please review

**Comment by SeppoTakalo** [comment]
Did you check the compilation warnings here?

The designated initialisers are C99 features, which are not supposed to work on C++. At least not in C++11.

**Comment by artokin** [comment]
It looks like no warnings are generated currently:

GCC_ARM compilation

```
[Warning] @,: Compiler version mismatch: Have 7.3.1; expected version >= 6.0.0 and < 7.0.0
Building project nanostack-border-router (K64F, GCC_ARM)
Scan: nanostack-border-router
Compile [  0.1%]: at24mac.cpp
Compile [  0.2%]: NanostackRfPhyAtmel.cpp
Compile [  0.4%]: coap_connection_handler.c
```


ARM compilation

```
Building project nanostack-border-router (K64F, ARM)
Scan: nanostack-border-router
Compile [  0.1%]: at24mac.cpp
Compile [  0.2%]: NanostackRfPhyAtmel.cpp
Compile [  0.4%]: coap_connection_handler.c

```

However, this part need to be changed if it is not c++ compatible.

**Comment by artokin** [comment]
IAR and ARMC6 compilers are not producing warnings:

IAR compilation
```
22:49:48 + mbed compile -t IAR -m K64F --app-config mbed_conf.json -c
22:50:34 Compile [  4.4%]: NanostackRfPhyAtmel.cpp
22:50:34 Compile [  4.5%]: Timer.cpp
```

ARMC6 compilation
```
22:48:13 + mbed compile -t ARMC6 -m K64F -j 0 --app-config ./configs/6lowpan_Atmel_RF.json --profile debug
22:48:40 Building project nanostack-border-router (K64F, ARMC6)
22:48:40 Scan: nanostack-border-router
22:50:34 Compile [  4.4%]: NanostackRfPhyAtmel.cpp
22:50:34 Compile [  4.5%]: Timer.cpp
```

**Pull request merged**
