### PR TITLE
Threading

### PR DESCRIPTION
**Pull request by kjbracey-arm**
Use a thread rather than interrupt if possible

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
@c1728p9, @sg-, @SeppoTakalo, @JarkkoPaso 

nanomesh-applications should also get the abstract locks and speed optimisation patches.

**Comment by kjbracey-arm** [comment]
@juhhei01

**Comment by SeppoTakalo** [comment]
+1
I like this. Looks like proper driver now, with interrupt flags and worker thread instead of transferring data in interrupt.

**Comment by kjbracey-arm** [comment]
@yogpan01

**Comment by yogpan01** [comment]
@kimlep01 @SeppoTakalo : This needs to be tested with mbed-client-quickstart example again to verify that this PR doesn't break anything.

**Comment by kjbracey-arm** [comment]
Our tests have been with mbed-client-quickstart-example, so should be sort of okay, but will want stability testing. clitest should be checked too.

**Comment by juhhei01** [comment]
@kjbracey-arm +1 Do you have some instructions how to test new setup? I have time now for testing and football.

**Comment by kjbracey-arm** [comment]
Last-commit is rebased https://github.com/ARMmbed/atmel-rf-driver/pull/32 in case we want both to go in (they conflict).

**Pull request merged**
