### PR TITLE
Now pins can be configured from any config.json 

### PR DESCRIPTION
**Pull request by javier-moreno-tridonic-com**
Default pins for the mbed 6LoWPan shield provided otherwise.

Configuration can be made by filling the following structure in the config.json or the "config" field of the target.json file
```
"atmel": {
    "rf": {
        "spi": {
            "mosi": "",
            "miso": "",
            "sclk": "",
            "cs": "",
            "rst": "",
            "slp": "",
            "irq": ""
        },
        "i2c": {
      	    "sda": "",
      	    "scl": ""
        }
    }
}
```

### CODE REVIEW

**Comment by 0xc0170** [comment]
Should fix #8 . Can you fix the formatting in driverAtmelRFInterface.cpp ? I suspect there are tabs for SPI object definition

Please can you edit the message (code highlight the config).

**Comment by javier-moreno-tridonic-com** [comment]
Oops, sorry about that. Done and done :)

**Comment by javier-moreno-tridonic-com** [comment]
Just checking in. Is there anything more that needs to be done?

**Comment by mlnx** [comment]
@SeppoTakalo 
Please review this request and comment if you see any problem.
Otherwise please merge. Thanks

**Pull request merged**
