### PR TITLE
Add support for IAR

### PR DESCRIPTION
**Pull request by c1728p9**
Add support for IAR by adding a nop using IAR syntax.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
You'll have to redo this - there's an incoming total replacement assembler routine in pull request #20. Need to do the whole routine, not just the NOP, I'm afraid.

**Comment by c1728p9** [comment]
Done

**Comment by c1728p9** [comment]
@SeppoTakalo, @kjbracey-arm are these real build failures?  If not this patch should be ready to merge.

**Comment by kjbracey-arm** [comment]
Do this properly - IAR seems to take same basic syntax as GCC for operands. Just need to leave off the underscores, I think.

**Pull request merged**
