### PR TITLE
Compile better

### PR DESCRIPTION
**Pull request by kjbracey-arm**
Two build improvements - be more platform-sensitive, and build-config sensitive

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
@yogpan01, @SeppoTakalo, @jaustin, @c1728p9, @geky

**Comment by kjbracey-arm** [comment]
Is TARGET_FF_ARDUINO defined in all the systems we care about?

**Comment by c1728p9** [comment]
Looks good to me.  I don't know about TARGET_FF_ARDUINO.

**Comment by SeppoTakalo** [comment]
+1

**Comment by kjbracey-arm** [comment]
TARGET_FF_ARDUINO wasn't working in Yotta - assume we can always compile in that case - shouldn't be included unnecessarily.

**Pull request merged**
